### ISSUE TITLE
Core not enabling with starfinder

### ISSUE THREAD

**Issue by 42Firehawk** [Saibot393/enhancedcombathud-sfrpg#3]
![image](https://github.com/user-attachments/assets/e3781d6b-b4ee-4ddb-a1ad-d0b52cfdb409)
As can be shown in the image, attempting to enable the combat hud fails due to the dependency not being enabled, but that can only be enabled automatically with the starfinder module.

**Comment by Saibot393** [comment]
That is strange, which version of the Starfinder System and which Foundry version are you using?

**Comment by 42Firehawk** [comment]
Starfinder version: 0.26.1
Foundry version: 12 build 331

**Comment by Saibot393** [comment]
Just to make sure, do you have [lib - color settings ](https://foundryvtt.com/packages/colorsettings) installed?

**Comment by 42Firehawk** [comment]
I did not, somehow it was not listed as a required dependency with how I installed. Sorry for taking your time.

**Comment by Saibot393** [comment]
No problem, glad to hear that it is solved.
