### ISSUE TITLE
Support for Pathfinder 1e

### ISSUE THREAD

**Issue by Kixel** [Saibot393/enhancedcombathud-sfrpg#4]
Yes, I know this is probably the wrong place to ask this - but I haven't really found a better spot.

I saw you released a bunch of Argon modules for different systems - including starfinder. I was wondering if support for PF1e would be possible. I have briefly looked into this repository to see if I could port this for pf1e (my understanding is the systems are somewhat similar) but didn't get very far at all.

Is support for PF1e possible - I'd love to help if needed.

**Comment by Saibot393** [comment]
As far as i am aware there already is a [PF1e module](https://foundryvtt.com/packages/enhancedcombathud-pf1) for Argon, which incidentally seems to have used some of this modules code as a base.

**Comment by Kixel** [comment]
Ok, how TF did I not find this.
Apparently this is exactly what I was looking for.
I'll close this as completed. Maybe someone else is too dumb to find this the normal way and stumbles on this issue.
Thanks.
